# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75e882f3cb853bdc28d2b00f9526b0bd8643c2611762784e3a34bc52d55c642b82e32fe98a65a13275c15bf72ae97bc3326ad14794a618a75a7f00a60a70e22c

test:
  secret_key_base: 1a290e53d27ca31aac9526c9758110a571a3854a7b8648f52d8d34d2d0eba03959214fa8ddb289dece1d03e0934c7137e1c8ff3cf16ae81a6b46ae6dcb64252e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
